### ISSUE TITLE
Admin Group Design

### ISSUE THREAD

**Issue by lexiyip429** [calvinckho/restvo-app#109]
https://www.figma.com/file/6fG3TYWZ39X6nzl0haU5EP/group?node-id=0%3A1

**Comment by calvinckho** [comment]
Hi @lexiyip429, I added you as an admin in Movement Church's Small Group Ministry. 

https://app.restvo.com/app/manage/activity/5ea1e6a16240cd58bb82a5ad/groups/5ea1e6a16240cd58bb82a5ad;categoryId=5e9fe35cc8bf1a622fec69d7

Please see the existing design and functions for the Groups view. I think we'll likely develop/design along this basic rubric because it is already being used in the other Program types. You may want to help us build out the multi-select options since it is not fully built out yet.

![Screen Shot 2020-07-23 at 1 03 30 PM](https://user-images.githubusercontent.com/23274587/88333334-eb450400-cce4-11ea-954d-f74db39ba3d2.png)

adding @alexandertsung  to this so he is in the loop
