### ISSUE TITLE
Chat Truncation Error

### ISSUE THREAD

**Issue by lorneez** [calvinckho/restvo-app#128]
There is an error in the chat messages where the message is truncated unnaturally.

**Comment by calvinckho** [comment]
the message to reproduce this: "The Angular Compiler requires TypeScript >=3.4.0 and <3.5.0 but 3.5.3 was found instead"

the truncation happens when santizeHtml discard anything after <3, thinking that it is a tag <3> </3>. I have turned on santizeHtml: disallowedTagsMode: 'recursiveEscape' so content will be preserved in <3> content </3>. But because <3 is not closed, the content after it is still discarded. 

This issue is closed for now. The chance of using <3 is slim. so it will be discarded for now, but all disallowed tags' content are preserved.
