### ISSUE TITLE
Implement default Program/Relationship detection

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/restvo-app#22]
Upon detecting a new user has joined her first Program/Community/Relationship (either actively or passively) that is not the default Restvo Community, automatically set the default program to it. It should also switch the landing page from Discover to Dashboard.

**Comment by davidloesch1** [comment]
<img width="1440" alt="Screen Shot 2020-04-02 at 10 05 26 AM" src="https://user-images.githubusercontent.com/16859476/78277778-e5bf7600-74c9-11ea-821f-0252ce131bcd.png">


Hi Calvin,

So let me see if I understand what you're looking for:
1. - you'd like me to remove the mentoring toggle feature
2.  - You'd like to know when someone has joined a new community (other than the default Restvo community)
3. - Youd like to know when someone has made their first relationship (does the gideon ho restivo count?  Im not sure what that is exactly)

4. I'm pretty sure you made a relationship with me on there, but is there a place I can see everyone who I have a relationship with?

5 . I'm not quite sure what you mean by set the "default program" to it.  What is the default program?

6.  Ok, so once they have joined a new community (for me, I chose church planters), you would like people to be directed to their dashboard instead of the discover pages, correct?

**Comment by calvinckho** [comment]
@davidloesch1 I merged your detection logic to the app-dev01 branch. Great work!

**Comment by calvinckho** [comment]
@davidloesch1 can you follow up with these cases/edge cases:
1) when a user leaves a community/program that he has set as default, revert back to the Discover state (e.g. UIMentoringMode = false) and also set defaultProgram back to Restvo. Also I added the local caching to storage (see my latest branch, moment.service.ts line 420) and you would need to update the cache as well.

**Comment by davidloesch1** [comment]
Hi calvin,

I'm not sure if this was intentional or not, but it seems like the 
app/discover/home/:id
<img width="1440" alt="Screen Shot 2020-04-16 at 10 17 42 AM" src="https://user-images.githubusercontent.com/16859476/79487061-80d94500-7fcc-11ea-8f00-c4576843641d.png">


and the 
app/activity/:id
<img width="1440" alt="Screen Shot 2020-04-16 at 10 18 00 AM" src="https://user-images.githubusercontent.com/16859476/79487128-9babb980-7fcc-11ea-80b6-622d5d835310.png">


are very similar, but somewhat confusing at first glance.  With the discover/home page, you don't have the dropdown menu to leave the activity, but on the app/activity page, you do.

would you want to make these two pages the same? or is that intentional that you wouldn't be able to leave the group from your dashboard and making the user go to the "me" page, then click on that activity, then leaving the group?


let me know if that question makes sense :)

**Comment by calvinckho** [comment]
Great question! It is intentional. 
<img width="934" alt="Screen Shot 2020-04-16 at 11 27 49 AM" src="https://user-images.githubusercontent.com/23274587/79492788-5344c980-7fd5-11ea-80c6-b07f2b5cac78.png">
BTW, your version of code is obsolete. Please pull the latest app-dev01 and see the latest Home button. See how the new 'discover/home/xxx' now has an edit action icon. The user can click on it to change the 'home' page. The user cannot leave a community from the Home page.
