### ISSUE TITLE
Restvo email notification bugs

### ISSUE THREAD

**Issue by calixo888** [calvinckho/restvo-app#54]
2 bugs I can see very quickly in Restvo email notifications

1. Messages overflow the container. Probably because the container has a fixed height
2. Links sent show the HTML "a" tag with it. 

[Image](https://www.dropbox.com/s/hz0s6uu4vr1acvy/Screenshot%202020-04-18%2020.07.57.png?dl=0)

**Comment by calvinckho** [comment]
Thanks @calixo888. We use handlebars to render and send template emails.

It is set to dynamic height. It renders everything correctly except anchor links. I am aware of this, as I failed to implement [innerHtml] in div in handlebar, so HTML tags aren't rendered correctly, hence the overflow. 

I will look more closely into it this week. In the meantime, have you worked with handlebars, and you know how to do innerHTML in handlebars? I am adding @xinluzhou @davidloesch1 @lorneez  here and see if any of you have any experience with handlebars.

**Comment by calixo888** [comment]
@calvinckho Where are the files located? I've never worked with handlebars, but I can figure it out. I just need to see the code first.

**Comment by calvinckho** [comment]
@lorneez  the template file is located in /restvo/templates/group-email/html.hbs.

the culprit lies in line 24
{{#if this.body}}

{{this.body}}
{{/if}}
the right way to do it in Angular HTML

{{#if this.body}}<div class="message" [innerHTML]="this.body">{{/if}}

But since this is not angular, we can't get the this.body to be assigned to the innerHTML property. Can you research how others assign value to innerHTML in handlebars?

**Comment by calvinckho** [comment]
thanks Lorne. I tried your solution but it didn't work. It turns out handlebar can render text unescaped using triple curly brackets {{{ this.body }}}. It solved the bug. 

Thanks for taking a stab at it.

**Comment by lorneez** [comment]
Hmm that is interesting. Does this work like this: the third set of curly brackets converts the initial
content of the double curly brackets into escaped characters?
