### ISSUE TITLE
desktop mouse pointer when hover over buttons becomes text edit pointer

### ISSUE THREAD

**Issue by gideon-ho** [calvinckho/restvo-app#55]

**Comment by calvinckho** [comment]
@xinluzhou can you add hover css on the secondary menu? See if you point you mouse over 'User Profile', 'About Me', it is a text edit pointer instead of a mouse pointer. 
I used ion-menu-toggle in the primary menu (see /front/src/app/app.component.html), but I used ion-item for the secondary menu items in /front/src/app/pages/user/user.page.html and that was the cause of it.
<img width="895" alt="Screen Shot 2020-04-20 at 11 41 18 PM" src="https://user-images.githubusercontent.com/23274587/79833625-9057e580-8360-11ea-9a32-49d02c946639.png">

**Comment by xinluzhou** [comment]
Hi Calvin, I think the problem is that all items in the secondary menu are not with a link, because when I changed <ion-item (click)="clickManageMenu('profile')"> to <ion-item [routerLink]="['/app/user/profile']", it turned out to be a mouse pointer , but the bold function was disabled. Do you still  want the item in second menu become bold after clicking or keeping it same as primary menu?

**Comment by xinluzhou** [comment]
I figure it out ! thanks
