### ISSUE TITLE
Youtube video fullscreen does not work on chrome

### ISSUE THREAD

**Issue by gideon-ho** [calvinckho/restvo-app#58]

**Comment by calvinckho** [comment]
@calixo888 can you take a quick look at it? It was an issue on a Chromebook's chrome browser, but it works okay on my MacBook Pro chrome.

**Comment by calvinckho** [comment]
I am assigning you to this. Can you test out the video full screen on safari, firefox, edge (if you have it), mobile browser, android Restvo app, etc.? 
https://app.restvo.com/app/activity/5ebcdc1cb601a52009c89e5d;type=2;token=Q5AsFYSdNo

**Comment by Ananya157** [comment]
Hi Calvin,
I have tested this issue on Chrome, Firefox, Safari, Edge(both in mac OS and Windows ), Android App, IOS App, Mobile browser and it works fine.
There was one problem in Chrome in windows because of the old Chrome version.
For the Chrome version: 67.0.3396.99 it gave a blank white page when the video was in full screen with audio working fine, but later I updated the chrome version and it worked fine.
This issue maybe because of the older chrome version.
