### ISSUE TITLE
When leaving or deleting an Activity, update defaultProgram

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/restvo-app#60]
related to #22

**Comment by calvinckho** [comment]
@davidloesch1 what is the status on this? Did you get to implement this yet?

**Comment by calvinckho** [comment]
@davidloesch1 I checked the code and didn't see delete Activity detection being implemented yet. Can you try to add it?

**Comment by davidloesch1** [comment]
Ok, as I mentioned, I am not sure how I missed this, I thought I did this at some point and just lost track of it I guess???  Not sure, but I worked on it tonight and am almost there.  

it seems to work if you are a new user and join an activity, it changes your default "Restvo" to the activity you just joined.  Then, when you quit the new Activity, it goes back to "Restvo".  It is still very choppy.  Tomorrow, I will work on making it so that it detects which group you just left, compares it to what you userData.defaultProgram is and if they are not the same, do nothing, if they are the same, then switch the default to Restvo (?) or maybe something else (?)

We can talk tomorrow.  Cheers!

**Comment by davidloesch1** [comment]
Hi Calvin,

I think the logic is a little better after I had a play around with it.  Ultimately, I think we could logic the function down to be something that would be more useful on a global scale, but I think this works for a draft of it.  Let m know what you think.  Submitting a pull request now.
